# Generated by Django 2.0.2 on 2018-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180813_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
